### ISSUE TITLE
bluealsa question

### ISSUE THREAD

**Issue by stramazzo** [raspberrypi-ui/bluealsa#1]
Hi
I'm trying to use my helmet headset with a raspberry pi to use with crankshaft openauto.
I understood that there are two ways bluetoothctl + pulseaudio or bluetoothctl + bluez-alsa (now bluealsa).
I have a clean Raspbian-stretch 2018 03 13. I tried to install your git but the command 
"sudo  ../configure --enable-aac --enable-debug"
ends with 
"
checking for ALSA... no
configure: error: Package requirements (alsa) were not met:

No package 'alsa' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ALSA_CFLAGS
and ALSA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
"
I think alsa has now a different name (alsa-something) and doesn't get detected, can you help me out?
Thanks

**Comment by spl237** [comment]
Try installing libasound2-dev - that's the dev files for the ALSA libraries. The ALSA libraries themselves are in the package libasound2.

"sudo apt-get build-dep bluealsa" should install all the build dependencies for the package.

**Comment by stramazzo** [comment]
@spl237 Thanks
apt-get install dh-autoreconf solved the alsa missing error.
apt-get build-deb bluealsa gives this:
E: you must pur some 'source' URIs...
sources.list deb-src is uncommented.

Now ../configure... Stops at:
No package "bluez"

Sudo apt-get install bluez
Bluez is already the newest version (5.43-2+rpt2+deb9u2)

Thank you for your help.
It is a great learning experience for me.

**Comment by spl237** [comment]
You need to install libbluetooth-dev - this should have been installed by "sudo apt-get build-dep bluealsa", so that seems not to have worked. You need to uncomment deb-src in all the files in /etc/apt/sources.list.d/ as well as in /etc/apt/sources.list, and you need to do "sudo apt-get update" once you have uncommented the lines.

**Comment by stramazzo** [comment]
Thanks, but still stuck. This is what i did:
"
Raspbian 2018 03 13 Fresh install

sudo nano /etc/apt/sources.list
uncomment #deb-src -> deb-src

sudo nano /etc/apt/sources.list.d/raspi.list
uncomment #deb-src -> deb-src

sudo apt-get update
sudo apt-get upgrade

sudo reboot

sudo apt-get update
sudo apt-get build-dep bluealsa

sudo git clone https://github.com/raspberrypi-ui/bluealsa

cd bluealsa
sudo autoreconf --install
sudo mkdir build && cd build
sudo ../configure --enable-aac --enable-debug
"
and I get:
"
...
checking for AAC... no
configure: error: Package requirements (fdk-aac >= 0.1.1) were not met:

No package 'fdk-aac' found
"

**Comment by spl237** [comment]
That's because you are enabling AAC support, which is optional and not used in our implementation, so it isn't a build dependency which we install. Remove "--enable-aac" from the configure command line.

**Comment by stramazzo** [comment]
Now it is working.
Thanks!
