### ISSUE TITLE
Playing only loud noise

### ISSUE THREAD

**Issue by stefanofornari** [raspberrypi-ui/bluealsa#7]
Hello,
after finally managing to build and installing I ran aplay. The good news is that the rpi now is definitely using the speaker, but I hear only very loud noise. Any hint/help?

thanks in advance

**Comment by stefanofornari** [comment]
It was because it was a mp3... does aplay play only wav? how can I use omxplayer?

**Comment by spl237** [comment]
This is not an issue with the package - pleaase open a thread on the forums if you want help with this sort of thing.
